config/routes.rb
Grupki::Application.routes.draw do
  devise_for :users
  
  resources :groups do
    resources :memberships
  end
  
  resources :groups do
    resources :membership_requests
  end
  

    
  resources :users do
    resources :membership_requests
  end
  
  resources :users do
    resources :memberships
  end
  resources :memberships
  
  resources :membership_requests do
    member do
      get 'accept'
    end
  end
  

  root :to => "groups#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :membership_requests, :dependent => :destroy
  has_many :users, :through => :memberships 
  def admins
    memberships.where(:admin => true).map {|t| t.user}
  end
      
  def admin?(user)
    admins.include?(user)
  end
      
  def members
    memberships.map {|t| t.user}
  end
  
  def member?(user)
    members.include?(user)
  end
end

app/models/group_admin.rb
class GroupAdmin < ActiveRecord::Base
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/membership_request.rb
class MembershipRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :membership_requests
  has_many :groups, :through => :memberships
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/group_admins_controller.rb
class GroupAdminsController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :load_group, :except => [:new, :index, :create]
  before_filter :authenticate_user!, :except => [:index]
  attr_reader :per_page
  
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(params[:group])
    if @group.save
      @membership = @group.memberships.create(:user_id => current_user.id, :admin => true)
      if @membership.save
        redirect_to group_path(@group)
      else
        @group.delete
        render :action => 'new'
        end
    else
      render :action => :new
    end
  end

  def index
    @search = Group.search(params[:search])
    @groups = @search.paginate(:page => params[:page], :per_page => 2)  
  end

  def show
    @users = @group.users
  end
  
  def edit
  end
  
  def update
     @group.update_attributes(params[:group])
     redirect_to @group
   end
  
  def destroy
    @group.destroy
    redirect_to groups_path
  end

private 

	def load_group
	  @group = Group.find(params[:id])
  end
end

app/controllers/membership_requests_controller.rb
class MembershipRequestsController < ApplicationController
  def create
     @membership_request = current_user.membership_requests.build(:group_id => params[:group_id])
     #@membership_requests = MembershipRequest.create(:user => current_user, :group_id => params[:group_id])
     if @membership_request.save
       flash[:notice] = "oczekiwanie na dodanie do grupy"
       redirect_to groups_path
     else
       flash[:notice] = "spierdzielilysmy=p"
     end
   end
   
   def accept
    #membership_request = current_user.membership_requests.find(params[:id])
    membership_request = MembershipRequest.find(params[:id])
    user = membership_request.user
    group = membership_request.group
    #membership = Membership.new(:user => user, :group => group)
    membership = group.memberships.create(:user => user)
    if membership.valid?
      membership_request.destroy
      redirect_to group_path(group)
    else
      flash[:notice] = "akceptacja nie powiodla się"
      redirect_to group_path(group)
    end
    #dodanie użytkownika który prosił o dodanie do grupy(do grupy do której chciał) przez administratora tej grupy
   end

   def destroy
     @membership_request = current_user.membership_requests.find(params[:id])
     @membership_request.destroy
     redirect_to groups_path
   end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  
  def create
    @membership = current_user.memberships.build(:group_id => params[:group_id])
    if @membership.save
      flash[:notice] = "dodano do grupy"
      redirect_to group_path(@membership.group) 
    else
      flash[:notice] = "spierdzielilyscie=p"
    end
  end
    
  def destroy
    @membership = current_user.memberships.find(params[:id])
    @membership.destroy
    redirect_to groups_path
  end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = User.all
  end
  
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_admins_helper.rb
module GroupAdminsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/membership_requests_helper.rb
module MembershipRequestsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
- if @group.errors.any?
  #errorExplanation
    %h2
      = pluralize(@company.errors.count, "error")
    %ul  
    - @company.errors.full_messages.each do |msg|
      %li= msg
%p= f.label :name, "Nazwa grupy"
%p= f.text_field :name
%p= f.label :description, "Opis grupy"

%p= f.text_area :description

app/views/groups/_form2.html.haml
%p= f.label :name_contains, "Wyszukaj grupe , ktora zawiera w nazwie slowo:"
%p= f.text_field :name_contains

app/views/groups/edit.html.haml
- form_for @group do |f|
  = render :partial => "form", :locals => {:f => f}
  = f.submit "Zmien"

app/views/groups/index.html.haml
%h2 Grupy
%p= link_to "Wyloguj mnie", destroy_user_session_path
%hr
- form_for @search, :url => groups_path, :html => {:method => :get} do |f|
  = render :partial => "form2", :locals => {:f => f}
  = f.submit "szukaj"
%hr
%p= link_to "Nowa grupa", new_group_path
%hr
- @groups.each do |group|
  %b= group.name
  %p= group.description
  = link_to "Wiecej", group
  %hr
%p= will_paginate @groups

app/views/groups/new.html.haml
- form_for @group do |f|
  = render :partial => "form", :locals => {:f => f}
  = f.submit "dodaj"

app/views/groups/show.html.haml
%h1= @group.name
%p= @group.description
%hr
%h2= "Czlonkowie:"
- @group.users.each do |user|
    %p= "#{user.email}"
%hr
-if @group.member?(current_user)
    %p= "Jestes zapisany do grupy"
-else
    %p= link_to "Dolacz do grupy", group_membership_requests_path(@group.id), :confirm => "czy napewno chcesz dolaczyc?", :method => :post
  
-if @group.admin?(current_user)
    - @group.membership_requests.each do |request|
        %p= "mail proszacego: #{request.user.email}"
        %p= link_to "zatwierdz", accept_membership_request_path(request.id)
        
    %p= link_to "Edytuj", edit_group_path(@group)
    %p= link_to "Usun grupe", group_path(@group), :method => :delete
    
%p= link_to "Wszystkie grupy", groups_path
%p= link_to "Wyloguj mnie", destroy_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grupki</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <%= notice %>
  <%= alert %>

<%= yield %>

</body>
</html>